:Author: mapostle
:Email: mariaapostle1@gmail.com
:Date: 20/09/2020
:Revision: version#1
:License: Public Domain

= Project: Dinosaur Game

Describe your project

== Step 1: Installation
Download and extract the .zip file. Additionally, make sure you have the TimerOne library installed. 
This can be found at https://www.arduino.cc/reference/en/libraries/timerone/

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a Public Domain License.

=== Contributing
To contribute to this project please contact mapostle https://id.arduino.cc/mapostle

|===
| Part name          | Quantity
| Arduino Uno        | 1
| LCD Display        | 1
| 220 Ohm Resistor   | 2
| Pushbutton         | 2
| Potentiometer      | 1
| MtM Jumper Wires   | 8
| MtF Jumper Wires   | 12
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
